clients = 10
replicas = 4
payload-size = 5
duration = "10s"
metrics = ["client-latency", "throughput","read-throughput"]
measurement-interval = "10s"
output = "./measurement"
# hosts = ["hs01",]
# log-level = "debug"

# [[hosts-config]]
# name = "hs01"
# internal-address = "172.21.160.130"