replicas = 4
clients = 4
client-timeout = "5s"
duration = "30s"
batch-size = 8
payload-size = 5
metrics = ["client-latency", "throughput","read-throughput"]
measurement-interval = "30s"
output = "./measurement"
hosts = ["hs01",]
# log-level = "debug"

[[hosts-config]]
name = "hs01"
internal-address = "172.21.160.130"