clients = 20
client-timeout = "5s"
replicas = 4
duration = "120s"
timeout-multiplier = 2
rate-step = 10
batch-size = 8
metrics = ["client-latency", "throughput"]
measurement-interval = "120s"
output = "./measurement"
# leader-rotation = "CWA"
byzantine = ["crash:1"]
log-level = "debug"