replicas = 10
clients = 20
client-timeout = "5s"
rate-step = 10
duration = "30s"
max-timeout = "5s"
batch-size = 8
payload-size = 5
metrics = ["client-latency", "throughput","read-throughput"]
measurement-interval = "30s"
output = "./measurement"
hosts = ["hs01","hs02","hs03","hs04","hs05",]
# log-level = "debug"

[[hosts-config]]
name = "hs01"
internal-address = "172.21.160.130"

[[hosts-config]]
name = "hs02"
internal-address = "172.21.160.133"

[[hosts-config]]
name = "hs03"
internal-address = "172.21.160.127"

[[hosts-config]]
name = "hs04"
internal-address = "172.21.160.132"

[[hosts-config]]
name = "hs05"
internal-address = "172.21.160.125"