clients = 20
client-timeout = "5s"
replicas = 4
payload-size = 5
duration = "30s"
timeout-multiplier = 2
rate-step = 10
batch-size = 8
metrics = ["client-latency", "throughput","read-throughput"]
measurement-interval = "30s"
output = "./measurement"
# leader-rotation = "CWA"
# byzantine = ["crash:1"]
# log-level = "debug"